### ISSUE TITLE
gandalf not found problem

### ISSUE THREAD

**Issue by Jichao** [fxfactorial/ocaml-usbmux#10]
After following the command, gandalf is not found.  
It seems that the opam does not insert .opam/system/bin/ into PATH environment variable. Maybe add this to the readme?

**Comment by fxfactorial** [comment]
@Jichao `opam` adds its own to the `PATH`. Most likely you have a out of sync switch, check `$ opam switch` and most like you'll need to do a `eval $(opam config env)`

**Comment by Jichao** [comment]
Thanks for your reply, `eval $(opam config env)` gives  `file config not found`. Anyway I manage to add it to system path manually.

**Comment by fxfactorial** [comment]
Okay glad you got it fixed but `file config not found` doesn't sound good. Can you give more output, like what exactly is printed when you do the `eval $(opam config env)`
